### ISSUE TITLE
Travis failures about missing scenario texts

### ISSUE THREAD

**Issue by PVince81** [owncloud/customgroups#107]
https://travis-ci.org/owncloud/customgroups/jobs/274121008

```
--- CustomGroupsContext has missing steps. Define them with these snippets:

    /**

     * @Given As an :arg1

     */

    public function asAn2($arg1)

    {

        throw new PendingException();

    }

    /**

     * @Given User :arg1 moved file :arg2 to :arg3

     */

    public function userMovedFileTo($arg1, $arg2, $arg3)

    {

        throw new PendingException();

    }

    /**

     * @When Updating last share with

     */

    public function updatingLastShareWith(TableNode $table)

    {

        throw new PendingException();

    }

    /**

     * @When Getting info of last share

     */

    public function gettingInfoOfLastShare2()

    {

        throw new PendingException();

    }

    /**

     * @Then Share fields of last share match with

     */

    public function shareFieldsOfLastShareMatchWith(TableNode $table)

    {

        throw new PendingException();

    }

    /**

     * @When Downloading file :arg1 with range :arg2

     */

    public function downloadingFileWithRange($arg1, $arg2)

    {

        throw new PendingException();

    }

    /**

     * @Then Downloaded content should be :arg1

     */

    public function downloadedContentShouldBe2($arg1)

    {

        throw new PendingException();

    }

    /**

     * @Given Deleting last share

     */

    public function deletingLastShare2()

    {

        throw new PendingException();

    }

    /**

     * @Given User :arg1 moves file :arg2 to :arg3

     */

    public function userMovesFileTo($arg1, $arg2, $arg3)

    {

        throw new PendingException();

    }
```

@SergioBertolinSG can you have a look ?

**Comment by PVince81** [comment]
I wonder if we should take "stable10" as core branch instead of master ?

**Comment by phil-davis** [comment]
PR #108

**Comment by SergioBertolinSG** [comment]
@PVince81 maybe we should have two jobs, one with core's master and one with core's stable10

**Comment by phil-davis** [comment]
and people (pointy hat to me) should fix dependent code when they change infrastructure in core master/stable10... 

But yes, in general it would be nice to know that app tests work on top of both core master and core stable10. For now that might be easy enough. In future there will be an expanding matrix of which ``stable10`` ``stable11`` core branches the "master" version of an app is supported on top of (and maybe some branches of the app repo that have an old version of the app that is in "maintenance mode" maintaining compatibility with and older but recent core)

**Comment by phil-davis** [comment]
This issue should be fixed now. When someone has rebased some PR to current master and confirmed that it is good, please close.

**Comment by SergioBertolinSG** [comment]
@PVince81 you already did it https://github.com/owncloud/customgroups/pull/84

**Comment by phil-davis** [comment]
PR #106 has been rebased and passes. So this issue is complete.
