### ISSUE TITLE
Missing img folder in makefile

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/customgroups#112]
With that folder missing the icon is missing.

https://github.com/owncloud/customgroups/blob/master/Makefile#L13-L14

cc @PVince81

**Comment by phil-davis** [comment]
Well spotted - this is an example of why some "final QA" needs to happen with the actual proposed release tarballs. And even after that, there needs to be some verification that the tarball finally put in the marketplace and that actually gets downloaded by real users is the correct one that works. (impossible to QA that last bit without actually releasing!)

**Comment by PVince81** [comment]
Great catch, I'll take care

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/customgroups/pull/113
