### ISSUE TITLE
User adding autocomplete should comply with sharing restrictions

### ISSUE THREAD

**Issue by pmaier1** [owncloud/customgroups#116]
When the global sharing restriction "Restrict users to only share with users in their groups" is active the "add users to a custom group" dialog autocomplete should only offer users that I'm allowed to share with (exactly like the sharing dialog autocomplete, but only for users, not groups or other share types).

**Comment by PVince81** [comment]
Same for the enumeration checkboxes.

**Comment by PVince81** [comment]
@pmaier1 fix is implemented
