### ISSUE TITLE
0.3.6 release plan

### ISSUE THREAD

**Issue by pmaier1** [owncloud/customgroups#119]
**Reason**
- Release needed for fix for user add autocomplete results to comply with sharing restrictions https://github.com/owncloud/customgroups/pull/117

**QA**
- [x] Create release branch
- [x] Create "$version Testplan" - https://github.com/owncloud/customgroups/issues/124
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label)

**Marketing**
- [x] Check/adapt info.xml stuff https://github.com/owncloud/customgroups/pull/126
- ~~Check/adapt screenshot~~
- ~~Blog post or other communication if applicable~~

**Documentation**
- ~~Changes in the docs needed?~~

**Build & Marketplace release**

- [x] Bump version in info.xml (https://github.com/owncloud/customgroups/commit/c5f25919d9d23ed56bb707ce508406b80b0d7a5d)
- [x] Change CHANGELOG.md 'Unreleased' to '$version'
- [x] Create github tag for '$version'
- [x] Build and sign tarball from github tag '$version'
- [x] Upload to marketplace
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Rename QA milestone to '$version' - https://github.com/owncloud/customgroups/milestone/14
- [x] Add a new 'Unreleased' section in CHANGELOG.md
- [x] Create PR to merge changes back to `master` -
 https://github.com/owncloud/customgroups/pull/128

**Specifics**

- Fixes https://github.com/owncloud/enterprise/issues/2280

**Comment by pmaier1** [comment]
Released. Closing.

**Comment by pmaier1** [comment]
Still need to merge this one https://github.com/owncloud/customgroups/pull/128
@patrickjahns please close here when done! thx

**Comment by pmaier1** [comment]
BTW. the changelog only has one entry but closed items in the milestone look like there has been more https://github.com/owncloud/customgroups/milestone/14?closed=1. On purpose?

**Comment by patrickjahns** [comment]
@pmaier1 
thanks for raising - these were changes that belonged to 0.3.5 - I've cleaned up the milestones and moved them accordingly
