### ISSUE TITLE
Empty screen

### ISSUE THREAD

**Issue by NoufIbrahim** [owncloud/customgroups#129]
hi,

i upgraded custom groups & now i cannot access the page, i click on it & it's empty.

**Comment by PVince81** [comment]
Please use the issue template https://raw.githubusercontent.com/owncloud/core/master/.github/issue_template.md

**Comment by PVince81** [comment]
Likely duplicate of https://github.com/owncloud/customgroups/issues/130. If you used the git version, please switch to the marketplace version instead.

If you did use the marketplace version, please reopen and fill the above issue template. Thanks.
