### ISSUE TITLE
OCA.CustomGroups.Templates is undefined

### ISSUE THREAD

**Issue by glannes31** [owncloud/customgroups#130]
Hello,

On an 10.0.3 owncloud's instance , we have a blank page when we want to use custom groups.

When i inspect the element , i have :

OCA.CustomGroups.Templates is undefined

Could you help me please?

**Comment by glannes31** [comment]
Okay when i replace with the marketplace app . It's not okay with gitclone .

**Comment by PVince81** [comment]
Yes, please always use the marketplace version for production.

For the git version, you need to run `make` and it is not suited for production use.
