### ISSUE TITLE
jQuery Core 1.9 Upgrade Guide

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/customgroups#153]
# jQuery Core 1.9 Upgrade Guide

Changes of Note in jQuery 1.9
See the full [upgrade guide at jquery.com](http://jquery.com/upgrade-guide/1.9/)

## Minor

`.trigger()`

- [x] js/GroupsView.js
- [x] js/MembersInputView.js
- [x] js/MembersView.js

`.focus()`

- [x] js/GroupsView.js
- [x] js/MembersView.js

`.ajax()`

- [x] js/MembersInputView.js

`.data()`

- [x] js/MembersInputView.js

`.focus()`

- [x] js/GroupsView.js
- [x] js/MembersView.js

`.attr()`

- [x] js/App.js
- [x] js/GroupsView.js
- [x] js/MembersInputView.js
- [x] js/MembersView.js
- [x] js/admin.js

`.prop()`

- [x] js/MembersView.js

`.before()`

- [x] js/GroupsView.js
- [x] js/MembersView.js

`.replaceWith()`

- [x] js/GroupsView.js
- [x] js/MembersView.js

**Comment by PVince81** [comment]
- [ ] BUG: the autocomplete seems broken when using the jquery-2-migration branch, but it works on master

**Comment by PVince81** [comment]
`.data()` works as the autocomplete works. Closing.
