### ISSUE TITLE
jQuery UI Upgrade

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/customgroups#163]
# jQuery UI Upgrade

See the full [upgrade 1.11. guide](https://jqueryui.com/upgrade-guide/1.11/)

See the full [upgrade 1.12. guide](https://jqueryui.com/upgrade-guide/1.12/)

## [1.11] (Core) Deprecated multiple

`.focus()`

- [x] js/GroupsView.js
- [x] js/MembersView.js

## [1.12] (Core) Removed multiple

`.focus()`

- [x] js/GroupsView.js
- [x] js/MembersView.js

## [1.12] (tooltip) CSS class changes

`.tooltip()`

- [x] js/GroupsView.js
- [x] js/MembersInputView.js
- [x] js/MembersView.js

**Comment by PVince81** [comment]
- tooltips still work
- focus usage has no param here
