### ISSUE TITLE
[For 10.1] Customgroups 0.4.0

### ISSUE THREAD

**Issue by PVince81** [owncloud/customgroups#170]
### Reason
- [Core platform switches to semver with 10.1](https://github.com/owncloud/core/pull/33242) so we set max-version to 10.1: https://github.com/owncloud/customgroups/pull/136
- Small fixes: https://github.com/owncloud/customgroups/pull/165
- PHP 7.2 support (confirmed only by tests, no code changes): https://github.com/owncloud/customgroups/pull/164

### QA
- [x] Create **QA Milestone**
- [x] Move items from `development` to `qa` 
- [x] Create release branch with the format "release-$version"
- [x] Create "0.4.0 Testplan" https://github.com/owncloud/customgroups/issues/190
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) https://github.com/owncloud/customgroups/issues/190

### Documentation
- [ ] Changes in the docs needed?

### Marketing
- [ ] Ping RocketChat channel #marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build & Marketplace release

All actions to be done on the release branch from here:
- [x] Bump version in info.xml: https://github.com/owncloud/customgroups/pull/189
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version - $currentDate' (ex: 3.1.5 - 2018-08-01): https://github.com/owncloud/customgroups/pull/189
- [x] Create github tag for 'v${version}RC1'
- [x] Build and sign RC tarball from github tag 'v${version}RC1' with `make dist` => https://cloud.owncloud.com/index.php/s/sVIn0UDkELHe5vG
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing
- [x] Create github tag for final 'v${version}'
- [x] Build and sign final tarball from github tag 'v${version}' with `make dist`
- [x] Smoke test tarball (at least install + enable)
- [x] Upload to marketplace
- [x] Publish for customers
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Rename QA milestone to '$version'
- [x] Add a new 'Unreleased' section in CHANGELOG.md
- [x] Create PR to merge changes back to the `master` branch: https://github.com/owncloud/customgroups/pull/191

**Comment by PVince81** [comment]
- [ ] let's see if we can finish https://github.com/owncloud/customgroups/pull/146

**Comment by PVince81** [comment]
- [ ] CI issue https://github.com/owncloud/customgroups/pull/146
- [ ] build scripts cleanup: https://github.com/owncloud/customgroups/pull/173

**Comment by PVince81** [comment]
- [ ] Oracle failures: https://github.com/owncloud/customgroups/issues/175

**Comment by davitol** [comment]
@PVince81 Tarball is QA-ready

**Comment by PVince81** [comment]
@DeepDiver1975 please push https://cloud.owncloud.com/index.php/s/Jcnkoa3R7gGDH9N to marketplace

changelog here: https://github.com/owncloud/customgroups/blob/release-0.4.0/CHANGELOG.md#040
