### ISSUE TITLE
Make it possible to add guest accounts to custom groups

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/customgroups#198]
In the member administration of a custom group it would be nice to be able to add guest accounts on the fly (If Guest Accounts are installed and enabled). I'd expected the same behaviour as on creating a share just by entering the email address: "Add abc@example.com (guest)".

![image](https://user-images.githubusercontent.com/16665512/51991395-51afe400-24ab-11e9-9743-e34b115568ef.png)

**Comment by pmaier1** [comment]
This conflicts with the current concept of guests as they are created by sharing with them. Adding a user to a custom group does not imply sharing. Anyway, makes sense and I take the idea for future user/group management concepts.
