### ISSUE TITLE
Users don't get deleted from group when accounts is deleted

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/customgroups#200]
User "florian@" (guest account) was deleted by admin in user administration but is still in the custom group. Intended?

![image](https://user-images.githubusercontent.com/16665512/52136702-fca9d480-2648-11e9-8393-640b0a954d94.png)

@pmaier1

**Comment by hurradieweltgehtunter** [comment]
After removing him from the group (trash bin icon) and reloading the page the user is still in the group.

**Comment by pmaier1** [comment]
Known issue https://github.com/owncloud/customgroups/issues/59
