### ISSUE TITLE
Custom Groups 0.4.1

### ISSUE THREAD

**Issue by PVince81** [owncloud/customgroups#201]
### Reason
- [x] validation for group creation: https://github.com/owncloud/customgroups/pull/197 @davitol **Test steps: https://github.com/owncloud/customgroups/pull/197#issue-248801504**
- [ ] others ?

### QA
- [x] Create **QA Milestone**
- [x] Move items from `development` to `qa` 
- [x] Create release branch with the format "release-$version"
- [x] Test Changelog and smoke test "Custom Groups 0.4.1. " #216

### Documentation
- [ ] Changes in the docs needed?

### Marketing
- [ ] Ping RocketChat channel #marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build & Marketplace release

All actions to be done on the release branch from here:
- [x] Bump version in info.xml
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version' (final release date unknown)
- [x] Create github tag for 'v${version}RC1'
- [x] Build and sign RC tarball from github tag 'v${version}RC1' with `make dist` and upload as Github release: https://github.com/owncloud/customgroups/releases/tag/v0.4.1RC2
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing
- [x] Create github tag for final 'v${version}'
- [x] Build and sign final tarball from github tag 'v${version}' with `make dist` and upload as Github release
- [x] Smoke test tarball (at least install + enable)
- [x] Upload to marketplace
- [x] Publish for customers
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Rename QA milestone to '$version'
- [x] Add a new 'Unreleased' section in CHANGELOG.md and add release date '$version - $currentDate' (ex: 3.1.5 - 2018-08-01)
- [x] Create PR to merge changes back to the `master` branch

### Specifics

- Open tickets before QA can start
- Other specifics for app release

**Comment by PVince81** [comment]
RC is ready: https://github.com/owncloud/customgroups/releases/tag/v0.4.1RC2 (skipped RC1 due to changelog issue) @davitol

**Comment by davitol** [comment]
https://github.com/owncloud/customgroups/pull/197#issuecomment-470077204 After talking with @sharidasan we consider we can postpone the release and fix that part. Even more when the only item of the changelog is that PR

**Comment by PVince81** [comment]
@sharidas please port your fix to the release-0.4.1 branch

**Comment by sharidas** [comment]
Created PR against branch release-0.4.1 https://github.com/owncloud/customgroups/pull/212

**Comment by PVince81** [comment]
RC3 with the fix: https://github.com/owncloud/customgroups/releases/tag/v0.4.1RC3

**Comment by dpakach** [comment]
CustomGroups testplan #216
Everything works fine but there are some small bugs in the UI.
Raised at #217

**Comment by individual-it** [comment]
taking off QA-team label as QA is done here
