### ISSUE TITLE
It is possible to rename custom group names and bypass the validations

### ISSUE THREAD

**Issue by davitol** [owncloud/customgroups#208]
We added validations for names  in the group creation in this PR: https://github.com/owncloud/customgroups/pull/197 , but we should add them too to he edition.

![screen shot 2019-03-06 at 12 38 08](https://user-images.githubusercontent.com/10596560/53879990-19527700-4010-11e9-9c04-ed5175e9bea8.png)

**Comment by sharidas** [comment]
Created PR here:
- [x] https://github.com/owncloud/customgroups/pull/209 ( master branch )
