### ISSUE TITLE
Custom Groups 0.5.0

### ISSUE THREAD

**Issue by micbar** [owncloud/customgroups#266]
### Reason

- Release needed for https://github.com/owncloud/enterprise/issues/3555
- Release needed for https://github.com/owncloud/enterprise/issue/3526

### QA

- [x] Create **QA** Milestone and set the description to $version
- [x] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [x] Create "0.5.0 Testplan" @davitol https://github.com/owncloud/customgroups/issues/280

### Documentation

- [x] Changes in the docs needed?

### Marketing

- [ ] Ping @owncloud/marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build

All actions to be done on the release branch from here:
- [x] Bump version in info.xml (no version suffix)
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version' (final release date unknown)

#### Beta/RC

- [x] Create github tag for 'v${version}RC1' on release branch
- [x] Build and sign RC tarball from github tag 'v${version}RC1' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) @davitol https://github.com/owncloud/customgroups/issues/280

#### Final

- [x] Create github tag for final 'v${version}' on release branch
- [x] Build and sign final tarball from github tag 'v${version}' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [ ] Smoke test tarball (at least install + enable)

### Publishing

- [x] Upload tarball to marketplace (see handbook for details)
- [x] Publish tarball for customers (see handbook for details)
- [x] Send mail to release-coordination with link to this ticket and to the changelog

### Post-release

- [x] Rename QA milestone to '$version'
- [x] Add a new 'Unreleased' section in CHANGELOG.md and add release date '$version - $currentDate' (ex: 3.1.5 - 2018-08-01)
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number

**Comment by micbar** [comment]
@davitol moving to DEV again, because we need the Fif for the whitelisting from @sharidas

**Comment by micbar** [comment]
@davitol @jnweiger RC1 Created: https://github.com/owncloud/customgroups/releases/tag/v0.5.0RC1

**Comment by davitol** [comment]
>     * Changes in the docs needed?

We should document the change related to `'customgroups.disallowed-groups' => ['guest_app'],`

 @pmaier1 gave the go for writing the documentation (cc @settermjd maybe)


> @davitol @HanaGemela  RC1 Created: https://github.com/owncloud/customgroups/releases/tag/v0.5.0RC1

Tarball is QA-ready

**Comment by micbar** [comment]
@davitol @pmaier1 @settermjd There is one more setting.

`customgroups.disallow-admin-edit` 
This is a completely new feature, it was already shown in the reviews

**Comment by settermjd** [comment]
@micbar, the config setting is `customgroups.disallow-admin-access-all`, not `customgroups.disallow-admin-edit`, according to https://github.com/owncloud/customgroups/pull/273/files#diff-c8d4be5ecbca729f531c7848b5157a87R176.

**Comment by settermjd** [comment]
I'll get it documented today.

**Comment by settermjd** [comment]
> > ```
> > * Changes in the docs needed?
> > ```
> 
> We should document the change related to `'customgroups.disallowed-groups' => ['guest_app'],`
> 
> @pmaier1 gave the go for writing the documentation (cc @settermjd maybe)
> 
> > @davitol @HanaGemela  RC1 Created: https://github.com/owncloud/customgroups/releases/tag/v0.5.0RC1
> 
> Tarball is QA-ready

Sorry for overlooking this in the PR so far. Will add it in.

**Comment by settermjd** [comment]
Changes made.
