### ISSUE TITLE
Webdav API for groups management

### ISSUE THREAD

**Issue by PVince81** [owncloud/customgroups#3]
- [x] custom groups
    - [x] list groups PROPFIND http://localhost/owncloud/remote.php/dav/customgroups/groups/
        - [x] property `oc:display-name`: group display name
        - [x] child node `MembershipNode`, name is the custom group URI
    - [x] rename custom group: PROPPATCH oc:display-name on http://localhost/owncloud/remote.php/dav/customgroups/groups/$customGroupUri
        - [x] only group admin can rename
    - [x] delete group: DELETE http://localhost/owncloud/remote.php/dav/customgroups/groups/$customGroupUri
        - [x] only group admin can delete
    - [x] create group: MKCOL http://localhost/owncloud/remote.php/dav/customgroups/groups/$customGroupUri
        - [x] throws MethodNotAllowed if already exists
        - [x] creator automatically becomes group admin and member
- [x] memberships:
    - [x] list members PROPFIND http://localhost/owncloud/remote.php/dav/customgroups/groups/$numericGroupId/
        - [x] child node "MembershipNode" name is user id
        - [x] property `oc:role` (int) whether this member is also a group admin
        - [x] only members can list members, others get 403 when listing collection contents
    - [x] add member: PUT http://localhost/owncloud/remote.php/dav/customgroups/groups/$numericGroupId/$userId
        - [x] only group admin can add members
    - [x] remove member: DELETE http://localhost/owncloud/remote.php/dav/customgroups/groups/$customGroupUri/$userId
        - [x] only group admin can remove members
        - [x] group admin cannot remove self if no other admin exists in the group
        - [x] a group member can remove themselves with the same API call to leave the group
    - [x] change admin role of a member: PROPPATCH http://localhost/owncloud/remote.php/dav/customgroups/groups/$customGroupUri/$userId of the `oc:role` property
- [x] list group memberships of a given user: PROPFIND http://localhost/owncloud/remote.php/dav/customgroups/users/$userId/$membership
    - [x] child node is `MembershipNode` where name is group id
    - [x] membership node has "oc:role" attribute
- [x] regular admins can do the same as group admins
- [ ] provider REPORT in addition to PROPFIND for pagination

**Comment by PVince81** [comment]
- [ ] REQUIRES: support for apps to register sabre plugins: https://github.com/owncloud/core/issues/26195

**Comment by DeepDiver1975** [comment]
I'd prefer to not work on the numeric ids on the dav api layer.
the numeric id is something we should keep internal.
let there be a uri name which will handle this.

see like caldav and carddav implement this.

This way you can also use the standard PUT for creation:
PUT  http://localhost/owncloud/remote.php/dav/customgroups/awesome-group

**Comment by PVince81** [comment]
@DeepDiver1975 so what happens on renaming, does the URL change ?
Do we need an additional column in the DB "webdav_id" ?

**Comment by DeepDiver1975** [comment]
> Do we need an additional column in the DB "webdav_id" ?

its named 'uri' in caldav and carddav.

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 so what happens on renaming, does the URL change ?

in caldav and carddav renaming is only possible on the displayname - the uri is static

**Comment by PVince81** [comment]
Hmm, indeed... I have this old calendar from OC 4 which I first called "test" then renamed to "Main". The DB still contains "test" as name, confused me a lot when setting up Webdav sync back then.

Ok, then:
- [ ] adjust spec to use "uri" (generated static group name)
- [ ] adjust PR https://github.com/owncloud/customgroups/pull/1 to provide the "uri" column and generate that name

**Comment by DeepDiver1975** [comment]
> generate that name

generate? in the server?
it's part of the url in PUT

**Comment by PVince81** [comment]
ok, so the client nees to generate it then at creation time and pass a if-match header to avoid overwriting an existing group, in which case 409 Precondition failed comes back and the client mzst then add '(2)' ti the uri until a non-existing name is found. (similar to the file upload logic)

**Comment by PVince81** [comment]
@DeepDiver1975 ok, I think I'll also use this "uri" on the group backend interface. So core will receive the group id as "customgroups_$uri" instead of "customgroups_$numericId".

**Comment by PVince81** [comment]
@DeepDiver1975 should we then get rid of the numeric id ? As per my last comment it doesn't make sense any more... 

We could then have the DB's primary key on the uri field.

**Comment by PVince81** [comment]
and hopefully no issues with too long indices and emojis in uri names ? 😉 

Since these are URIs I think emojis or unicode chars are URL-encoded anyway, but that would make them longer.

**Comment by PVince81** [comment]
Adjusted spec to use `$customGroupUri` instead of `$numericGroupId` and added a mention of `If-None-Match` for PUT creation.

**Comment by DeepDiver1975** [comment]
> We could then have the DB's primary key on the uri field.

caldav and carddav still use an integer based id as primary key and also for referencing the records.

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/customgroups/pull/7

**Comment by PVince81** [comment]
Talked with @DeepDiver1975 today and we decided to replace the REPORT filters with an actual endpoint with users and groups separated

- customgroups/users/$userId/$membership
- customgroups/groups/$groupUri/$membership

So querying a user's membership is a matter of PROPFIND on customgroups/users/$userId/

**Comment by PVince81** [comment]
- [ ] introduce new level for "users" and "groups"
- [ ] pagination with REPORT

**Comment by PVince81** [comment]
- [ ] user node extends \Sabre\DAVACL\Principal implements ICollection
- [ ] add resource type mappings: $server->resourceTypeMapping['\\Sabre\\CalDAV\\Notifications\\ICollection'] = '{' . self::NS_CALENDARSERVER . '}notification';
- [ ] rename is-admin => role, use integer with constants

**Comment by PVince81** [comment]
I've updated the PR and also updated the spec above to match the new deeper endpoint structure.

**Comment by PVince81** [comment]
Pagination raised here https://github.com/owncloud/customgroups/issues/16
