### ISSUE TITLE
Customgroups handlebars are conflicting with the ones in core

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/customgroups#306]
customgroups apps brings its own handlebars which are conflicting with the ones in core
customgroups > core
0.5.1 is compatible with 10.4

Expected result: customgroups handlebars https://github.com/owncloud/customgroups/blob/master/package.json#L14 match server version of handlebars

**Comment by davitol** [comment]
* customgroups 0.5.1 installation from scratch + oC 10.3.2 => FAILS
* customgroups 0.5.1 upgrade from 0.4.X + oC 10.3.2 => FAILS

![Screen Shot 2020-02-06 at 10 54 11](https://user-images.githubusercontent.com/10596560/73926556-1e7b0e80-48d0-11ea-9bf7-97c1e1119f86.png)



** customgroups 0.5.1 installation from scratch + oC 10.4.0  RC1 => WORKS
** customgroups 0.5.1 upgrade from 0.5.0 + oC 10.4.0  RC1 => WORKS

**Comment by phil-davis** [comment]
That is surprising to me (that it works with 10.4.0RC1), because 10.4.0RC1 does not have the latest/matching handlebars version.

I guess 10.4.0RC1 has a "good enough" handlebars version.

**Comment by davitol** [comment]
> I guess 10.4.0RC1 has a "good enough" handlebars version.

Yes, that is also my thought. This PR https://github.com/owncloud/core/pull/36439  update handlebars for RC1 and that was good enough I guess
