### ISSUE TITLE
Custom groups 0.6.0

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/customgroups#307]
### Reason

- Release needed for https://github.com/owncloud/customgroups/issues/306

### QA

- [x] Generate Changelog
- [x] Create **QA** Milestone and set the description to $version
- [x] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [x] Create "0.6.0 Testplan" https://github.com/owncloud/customgroups/issues/307#issuecomment-583309460

### Documentation

- [x] Changes in the docs needed? If so create issue in owncloud/docs.

### Marketing

- [x] Ping @owncloud/marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build

All actions to be done on the release branch from here:
- [x] Bump version in info.xml (no version suffix)
- [x] Check php version dependency in info.xml
- [x] Check minimum ownCloud version dependency in info.xml
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [x] Create github tag for 'v${version}RC1' on release branch
- [x] Build and sign RC tarball from github tag 'v${version}RC1' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => @davitol https://github.com/owncloud/customgroups/issues/307#issuecomment-583309460

#### Final

- [x] Check that no documentation issues are pending
- [x] Rename last RC tarball to final
- [x] Create github tag for final 'v${version}' on release branch
- [x] Upload as Github release using changelog entries

### Publishing

- [x] Upload tarball to marketplace (see handbook for details)
- [x] Publish tarball for customers (see handbook for details) - customer.owncloud.com and portal.owncloud.com
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Copy email to rocket chat #updates channel

### Post-release

- [x] Rename QA milestone to '$version'
- [x] Add a new 'Unreleased' section in CHANGELOG.md
- [x] Make sure, the current changelog section has a date '$version - $currentDate' (ex: 3.1.5 - 2018-08-01)
- [x] Create PR to merge changes back to the `master` branch 
- [x] Close the milestone
- [x] Ensure [release template](https://github.com/owncloud/handbook/edit/master/modules/ROOT/examples/releases/server_app_release_template.md) is up to date
- [x] Add tests against stable to CI again

**Comment by HanaGemela** [comment]
@davitol RC1 available in https://github.com/owncloud/customgroups/releases/tag/v0.6.0RC1

**Comment by davitol** [comment]
## Test Results

10.4.1 RC1

- [ ] Fresh installation of customgroups 0.6.0.
- [ ] Upgrade from customgroups 0.5.0.
 [ ] Upgrade from customgroups 0.4.1.

10.3.X

- [ ] Try to install / upgrade to customgroups 0.6.0 and check it is not possible

- [ ] Sanity tested customgroups app

**Comment by davitol** [comment]
@HanaGemela customgrouos 0.6.0 RC1 tarball is QA-ready, See tests results in comment above. 

Ship it :shipit:

**Comment by pmaier1** [comment]
Merge back still missing here.
