### ISSUE TITLE
Run the tests against latest stable again 

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/customgroups#309]
@phil-davis please run the tests against latest stable again https://github.com/owncloud/customgroups/pull/308#issuecomment-583109286

**Comment by phil-davis** [comment]
This will be blocked until 10.4 release, when the "latest" download link is for a 10.4 iamge.

**Comment by phil-davis** [comment]
Unassigned myself - I don't want this in my assigned issues list until it gets to be unblocked
