### ISSUE TITLE
Custom Groups Release 0.6.1

### ISSUE THREAD

**Issue by phil-davis** [owncloud/customgroups#368]
##Reason 

PR #367 "[Security] Bump http-proxy from 1.16.2 to 1.18.1"

Does the security issue apply to the use in this repo?

If so, should a release be done?

(There seems to be not much else changed in master since 0.6.0 - just some translations and dependency version bumps)
Also #380 "[Security] Bump js-yaml from 3.10.0 to 3.14.1" - the same questions as above.

### Product approval 

- [ ] Verify transifex commits are in master: If a folder https://github.com/owncloud/<APPNAME>/tree/master/l10n exists, then https://drone.owncloud.com/owncloud/<APPNAME> should receive nightly '[tx] updated from transifex` ...
- [ ] Ping pmaier to check `info.xml` description and screenshot
- [ ] Get approval on translations from pmaier - send the date of the last tx commit from drone to Patrick

### QA

- [x] Generate Changelog
- [x] Create **QA** Milestone and set the description to $version
- [ ] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [x] Create "$version Testplan" https://github.com/owncloud/customgroups/issues/368#issuecomment-793124267 
- [ ] copy new/reopened issues from the previous release ticket as 'Issues to review' below.

### Documentation

- [ ] Changes in the docs needed? If so create issue in owncloud/docs.

### Marketing

- [ ] Ping @owncloud/marketing

### Build

All actions to be done on the release branch from here:
- [x] Bump version in `info.xml` (no version suffix)
- [x] Check php version dependency in `info.xml`
- [x] Check minimum ownCloud version dependency in `info.xml`
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [x] Create github tag for `v${version}RC1` on release branch
- [x] Build and sign RC tarball from github tag `v${version}RC1` (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [ ] Check that no documentation issues are pending
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries
- [ ] Ping `#marketing` channel to coordinate publishing

### Publishing

- [x] Upload tarball to marketplace (see handbook in confluence for details)
- [x] Publish tarball for customers (see handbook in confluence for details) - https://customer.owncloud.com and https://portal.owncloud.com
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Copy email to rocket chat `#updates` channel

### Post-release

- [x] Rename QA milestone to `$version`
- [x] Add a new 'Unreleased' section in CHANGELOG.md (and also update links at the bottom!)
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number
- [x] Close the milestone
- [x] Ensure [release template](https://github.com/owncloud/administration-internal/edit/master/tools/release/templates/server_app_release_template.md) is up to date

**Comment by phil-davis** [comment]
Also #380 "[Security] Bump js-yaml from 3.10.0 to 3.14.1" - the same questions as above.

**Comment by jnweiger** [comment]
Yes, that justifies a patch release. Queued.

**Comment by jnweiger** [comment]
## Test plan 

* [ ] Enable the app 
        * [ ]   No problems found
* [ ] Disable and enable the app using CLI
        * [ ]   No problems found
* [ ] Create a custom group
        * [ ]   Custom group is created correctly
* [ ] Create an already existing custom group
        * [ ]   The group cannot be created again
* [ ] Delete a custom group
        * [ ]   The group is removed correctly
* [ ] Rename a custom group
        * [ ]   The group is renamed correctly
* [ ] As a non-admin member try to rename its custom group
        * [ ]   He cannot rename its custom group
* [ ] Get members of a group
        * [ ] Members are retrieved correctly 
* [ ] Check that the creator of a custom group becames admin automatically
        * [ ]   No problems found
* [ ] As a creator of a custom group add members
        * [ ]   Members are added correctly
* [ ] As non-admin member of a custom group try to add members
        * [ ]   Non-admin member cannot add members
* [ ] Check that all the UI elements are usable when browsing
   * [ ] safari         
   * [ ] chrome
   * [ ] firefox
   * [ ] edge
   * [ ] ie11

**Comment by GeraldLeikam** [comment]
> ## Test plan
> 
>     [x]  Enable the app
>       
>       [x]         No problems found
> 
>     [ ]  Disable and enable the app using CLI
>       
>       [ ]         No problems found
> 
>     [x]  Create a custom group
>       
>       [x]         Custom group is created correctly
> 
>     [x]  Create an already existing custom group
>       
>       [x]         The group cannot be created again
> 
>     [x]  Delete a custom group
>       
>       [x]         The group is removed correctly
> 
>     [x]  Rename a custom group
>       
>       [x]         The group is renamed correctly
> 
>     [x]  As a non-admin member try to rename its custom group
>       
>       [x]         He cannot rename its custom group
> 
>     [x]  Get members of a group
>       
>       [x]  Members are retrieved correctly
> 
>     [x]  Check that the creator of a custom group becames admin automatically
>       
>       [x]         No problems found
> 
>     [x]  As a creator of a custom group add members
>       
>       [x]         Members are added correctly
> 
>     [x]  As non-admin member of a custom group try to add members
>       
>       [x]         Non-admin member cannot add members
> 
>     [x]  Check that all the UI elements are usable when browsing
>       
>       * [ ]  safari
>       * [ ]  chrome
>       [x]  firefox
>       * [ ]  edge
>       * [ ]  ie11
> 
>     [x]  can custom groups have same name as normal groups
>       
>       [ ]  try custrom group named admin. Do users gain admin powers?

**Comment by GeraldLeikam** [comment]
## Test plan 

* [ ] Enable the app
   * [ ]        No problems found
* [ ] Disable and enable the app using CLI
   * [ ]        No problems found
* [ ] Create a custom group
   * [ ]        Custom group is created correctly
* [ ] Create an already existing custom group
   * [ ]        The group cannot be created again
* [ ] Delete a custom group
   * [ ]        The group is removed correctly
* [ ] Rename a custom group
   * [ ]        The group is renamed correctly
* [ ] As a non-admin member try to rename its custom group
   * [ ]        He cannot rename its custom group
* [ ] Get members of a group
   * [ ] Members are retrieved correctly
* [ ] Check that the creator of a custom group becames admin automatically
   * [ ]        No problems found
* [ ] As a creator of a custom group add members
   * [ ]        Members are added correctly
* [ ] As non-admin member of a custom group try to add members
   * [ ]        Non-admin member cannot add members
* [ ] Check that all the UI elements are usable when browsing
   * [ ] safari
   * [ ] chrome
   * [ ] firefox
   * [ ] edge
   * [ ] ie11
* [ ] can custom groups have same name as normal groups
   * [ ] try custrom group named admin. Do users gain admin powers?

**Comment by jnweiger** [comment]
## issues opened while testing

* [ ] #666 -- [QA] What is wrong
