### ISSUE TITLE
Makefile must sign app

### ISSUE THREAD

**Issue by PVince81** [owncloud/customgroups#37]
Make it possible to specify a key in an env variable and use that key with occ to sign the app.

We'll likely need such process to make it easier to release signed market apps.

CC @DeepDiver1975 @VicDeo

**Comment by DeepDiver1975** [comment]
Contacts and twofactor_totp use makefile to sign - https://github.com/owncloud/contacts/blob/master/Makefile#L52-L63

**Comment by DeepDiver1975** [comment]
feel free to adopt
