### ISSUE TITLE
Review automated tests for sharing with custom groups

### ISSUE THREAD

**Issue by phil-davis** [owncloud/customgroups#446]
There are already various test scenarios for creating shares to custom groups:
https://github.com/owncloud/customgroups/blob/master/tests/acceptance/features/apiCustomGroups/sharingCustomGroups.feature

But most of those scenarios just create the custom group and check that the status code in the response is good. They do not check that the share actually works for the share receiver.

- enhance the scenarios so that they check that the share receiver can use the share (download, upload, list, create a folder, delete)
- also check that permissions are obeyed (e.g. cannot upload or create folder in a read-only share)
- add scenarios for interactions with "normal" user and group shares (to make sure that the same resource can be shared to mixtures of users, groups and custom groups)

And think about other combinations of ways that custom groups can be used, and add reasonable test coverage.

(Can custom group shares have an expiration date? If so, then test it. If not, then test what happens when someone tries to set an expiration date)

**Comment by SwikritiT** [comment]
@phil-davis all the PR's for this issue have been merged, I think we can close this.

**Comment by phil-davis** [comment]
Agree - closing.
