### ISSUE TITLE
PHP unit v9 tests failing 

### ISSUE THREAD

**Issue by phil-davis** [owncloud/customgroups#463]
`phpunit` was updated to major version 9 in core PR https://github.com/owncloud/core/pull/39290

This repo uses that for the unit tests. Some tests now fail and need refactoring.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/customgroups/2031/3/4
```
There were 14 warnings:

1) OCA\CustomGroups\Tests\unit\Dav\GroupsCollectionTest::testListGroups
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.
...
```

**Comment by phil-davis** [comment]
@JammingBen I will raise an issue in each repo that has failing unit tests.
Are you able to look at these?

**Comment by JammingBen** [comment]
Sure, just assign them to me so I get notified 👍
