### ISSUE TITLE
Superadmin cannot add users to groups

### ISSUE THREAD

**Issue by PVince81** [owncloud/customgroups#50]
Whenever a superadmin (aka ownCloud admin) is not a group member, they should still be able to add members to existing groups.

Currently it fails on the backend.

**Comment by PVince81** [comment]
@SergioBertolinSG wasn't this covered by the integration tests ?

**Comment by SergioBertolinSG** [comment]
Yes, IIRC it worked well.

**Comment by SergioBertolinSG** [comment]
Ok, this specific case is not covered, I'll add it.
