### ISSUE TITLE
Improve notifications

### ISSUE THREAD

**Issue by PVince81** [owncloud/customgroups#53]
- Notifications
  - Create a group “qustom” as user “admin”, add user “test3” to group and promote to group admin
  - See notification below
    - Notification for being added should say “You have been added to group ‘qustom’ by ‘admin’.
    - Notification for promotion should say: “Admin” assigned ‘Group admin’ role for the group “qustom” to you.
    - For making a group admin a member again there is no notification → consistency ("Admin" assigned ‘Member’ role for the group “qustom” to you.)
![custom_groups_notification2](https://cloud.githubusercontent.com/assets/21193500/24759933/55106752-1ae7-11e7-84c4-e63d8fe5bdc5.png)

@pmaier1

**Comment by PVince81** [comment]
I'll also add a message about being removed from a group.

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/customgroups/pull/56

**Comment by pmaier1** [comment]
One thing I just discovered that is missing and could maybe be added: Notification for group deletion

**Comment by PVince81** [comment]
Who would receive this notification ? All members ?

**Comment by pmaier1** [comment]
Yes, I would say so

**Comment by PVince81** [comment]
Okay, seems we might need to use a different approach here.

So far we sent the notification directly at the time of action.

Here since we need to notify all members (which could be quite a lot), we might want to move this to a background job. If we don't, then the delete operation will take much longer for the user (spinner for a longer time).

**Comment by pmaier1** [comment]
> Okay, seems we might need to use a different approach here.
So far we sent the notification directly at the time of action.
Here since we need to notify all members (which could be quite a lot), we might want to move this to a background job. If we don't, then the delete operation will take much longer for the user (spinner for a longer time).

Yep, this definitely sounds like the right approach! It's not a blocker but should be added for completeness and consistency.

**Comment by PVince81** [comment]
Raised here https://github.com/owncloud/customgroups/issues/57.
The background job approach will introduce a bit more complexity.
