### ISSUE TITLE
Release customgroups 0.7.2

### ISSUE THREAD

**Issue by phil-davis** [owncloud/customgroups#579]
### Reasons

- Needed to go with server core 10.13 because of the Symfony 4 to 5 upgrade https://github.com/owncloud/core/issues/39630
- PR #578 made code changes needed for Symfony 5

Note: the change in that PR also works fine with server core 10.12 and before, so there should be no need to bump the core min-version.

The app can be released any time before 10.13 - it should work fine with any of the recent oC10 core releases.

**Comment by jnweiger** [comment]
https://github.com/owncloud/customgroups/releases/download/v0.7.2-rc.1/customgroups-0.7.2-rc.1.tar.gz

**Comment by jnweiger** [comment]
Release done as part of 10.13.0
