### ISSUE TITLE
Change wording for 'group admin' role

### ISSUE THREAD

**Issue by pmaier1** [owncloud/customgroups#58]
Should be called 'Group owner' to not confuse people with the general group admins (sub-admins).

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/customgroups/pull/67

**Comment by pmaier1** [comment]
Great! Please transfer that to the docs @owncloud/documentation-admin (why can't I mention @msetter here?). Basically you need to replace 'Group admin' with 'Group owner' in the context of custom groups. Thanks!

**Comment by michaelstingl** [comment]
@pmaier1 Better mention @settermjd

**Comment by pmaier1** [comment]
> @pmaier1 Better mention @settermjd

I don't get a suggestion for that as well.. well, nvm :)

**Comment by settermjd** [comment]
No dramas. I missed this in the chat last week. Will resolve it today.

**Comment by settermjd** [comment]
@pmaier1 perhaps I've not been added to the group/members list for the repo.
