### ISSUE TITLE
Update required for the Custom Groups market app

### ISSUE THREAD

**Issue by settermjd** [owncloud/customgroups#61]
In the screenshot below, in the Personal navigation list (1) the app name is spelled as "**Customgroups**". However, in the app title (2) (sorry, not sure of a better term) it's spelled "**Custom Groups**". 

The navigation list title needs to be changed to be consistent with the naming in the rest of the application.

![custom groups ui error](https://cloud.githubusercontent.com/assets/196801/25887062/c8a833c8-3560-11e7-8cb1-c39c3b9793c8.png)

**Comment by PVince81** [comment]
Ok, seems the prerequisite PR from core was merged https://github.com/owncloud/core/issues/27327 so it should be possible now.

**Comment by PVince81** [comment]
@sharidas can you take care of this ? See https://github.com/owncloud/core/issues/27327 to find out how it needs to be done

**Comment by sharidas** [comment]
Merged https://github.com/owncloud/customgroups/pull/62
