### ISSUE TITLE
Customgroups doesn't appear in settings after install it.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/customgroups#64]
### Steps to reproduce

1. Install customgroups from public marketplace.
2. Look for it in settings.

### Expected behaviour
It is there.

### Actual behaviour
It doesn't appear.

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
{"installed":"true","maintenance":"false","needsDbUpgrade":"false","version":"10.0.1.3","versionstring":"10.0.1 RC4","edition":"Enterprise","productname":"ownCloud"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes WND.

Tested using windows server 2008 R2 and windows 10.

**Are you using encryption:** 
No

**Logs**

### Client configuration

**Browser**
Chrome

**Logs**
```

```

**Comment by PVince81** [comment]
fixed in 0.3.1, verified by @pmaier1
