### ISSUE TITLE
Spinners do not disappear when we try to leave a group without an administrator

### ISSUE THREAD

**Issue by davitol** [owncloud/customgroups#69]
![screen shot 2017-06-07 at 14 03 20](https://user-images.githubusercontent.com/10596560/26877410-2481477c-4b8a-11e7-837b-c78b8224e1c6.png)

**Comment by felixboehm** [comment]
@felixheidecke can you assign and fix this? Timeline?

**Comment by PVince81** [comment]
I'll likely get this fixed more quickly as I know my way around this code...

**Comment by PVince81** [comment]
@felixheidecke I see you don't have many tasks, reassigning to you.
