### ISSUE TITLE
Add (2) when creating duplicate group name

### ISSUE THREAD

**Issue by PVince81** [owncloud/customgroups#77]
Whenever a user creates a new group, automatically append (2) or another number if the group list visible for this user already contains a similar entry. This is mostly for information purposes.
The user can still choose to rename the group back to the name.

Should not append anything if the group exists but is not visible for the current user.

Estimate: 1-3 days as we might have to tear up the server side implementation

**Comment by felixboehm** [comment]
need PM input and challenge of requirements @pmaier1

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/customgroups/pull/82
