### ISSUE TITLE
Notification when user added to a custom group contains &quot;

### ISSUE THREAD

**Issue by haukman** [owncloud/customgroups#81]
### Steps to reproduce
1. Allow notifications in your browser
1. Create a custom group
3. Watch notification

### Expected behaviour
The notification should not contain "&quot"

### Actual behaviour
This is how it looks:

![grafik](https://user-images.githubusercontent.com/25486818/28662236-b6ec6276-72b9-11e7-973c-ff663bf5e55a.png)

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)
10.0.1

**Comment by PVince81** [comment]
Does `&quot;` also appear in the notification under the bell icon ? If it doesn't then it's a bug in the notification app which doesn't properly processes quotes

**Comment by PVince81** [comment]
Confirmed: bug in the notifications app

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/notifications/pull/100

**Comment by PVince81** [comment]
Fixed in https://github.com/owncloud/notifications/pull/100, will require a new release of the notifications app.
