### ISSUE TITLE
Customgroups doesn't have a personalised icon

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/customgroups#85]
In settings:

![screen shot 2017-08-18 at 14 51 06](https://user-images.githubusercontent.com/9048796/29459629-dbf53fb2-8424-11e7-8835-cf3e079a0cb0.png)

It will require a new one.

And also the picture in the apps view:

![screen shot 2017-08-18 at 14 53 36](https://user-images.githubusercontent.com/9048796/29459677-20b0700e-8425-11e7-8a53-60b328d9b414.png)

@felixheidecke

**Comment by PVince81** [comment]
@felixheidecke can you find an icon ?

**Comment by felixheidecke** [comment]
I sure can. :-)
