### ISSUE TITLE
Closing the sidebar in the customgroups view makes clicks to be ignored.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/customgroups#88]
### Steps to reproduce

1. As admin user, create a custom group 'customgroup'.
2. Click on the customgroup row. See the sidebar open.
3. Close the sidebar.
4. Try to open the sidebar again. Try to open the right menu.

### Expected behaviour
Sidebar opens again and you can access the right menu.

### Actual behaviour
Clicking after closing sidebar is ignored.

![problem_customgroups_sidebar](https://user-images.githubusercontent.com/9048796/29557917-d4f401c2-872a-11e7-91d7-9f1671915c53.gif)

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
10.0.3beta1
{"installed":"true","maintenance":"false","needsDbUpgrade":"false","version":"10.0.3.0","versionstring":"10.0.3 beta","edition":"Community","productname":"ownCloud"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No.

**Logs**
```
```

### Client configuration

**Browser**
Chrome

cc @PVince81

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/customgroups/pull/96
